// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1635242517);
user_pref("app.update.lastUpdateTime.background-update-timer", 1635242757);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1635242637);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1635285597);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1635242877);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20210819174627");
user_pref("extensions.lastAppVersion", "5.0.96.3");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.zotero.dataDir", "/home/leno/Zotero");
user_pref("extensions.zotero.fileHandler.pdf", "/usr/bin/zathura");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.prefVersion", 2);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"L1\",\"sessionID\":\"fRAHH9aF\"}]");
user_pref("extensions.zotero.useDataDir", true);
user_pref("font.internaluseonly.changed", true);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1635247006);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1634901007);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1633604839);
